package com.sakuBCA.enums;

public enum LoanStatus {
    REJECT_MARKETING,
    RECOMMENDED_BY_MARKETING,
    REJECTED_BY_BRANCH_MANAGER,
    APPROVED_BY_BRANCH_MANAGER,
    REJECTED_BACK_OFFICE,
    DISBURSED_BY_BACK_OFFICE
}