INSERT INTO Features (name)
SELECT * FROM (VALUES
    ('FEATURE_ADD_BRANCHES'),
    ('FEATURE_GET_ALL_BRANCHES'),
    ('FEATURE_GET_BRANCHES_BY_ID'),
    ('FEATURE_EDIT_BRANCH'),
    ('FEATURE_ADD_EMPLOYEE'),
    ('FEATURE_GET_ALL_EMPLOYEES'),
    ('FEATURE_GET_EMPLOYEE_BY_ID'),
    ('FEATURE_EDIT_EMPLOYEE'),
    ('FEATURE_ADD_CUSTOMER'),
    ('FEATURE_GET_ALL_CUSTOMERS'),
    ('FEATURE_GET_CUSTOMER_BY_ID'),
    ('FEATURE_EDIT_CUSTOMER'),
    ('FEATURE_ADD_ROLE'),
    ('FEATURE_GET_ALL_ROLES'),
    ('FEATURE_GET_ROLE_BY_ID'),
    ('FEATURE_EDIT_ROLE'),
    ('FEATURE_ASSIGN_FEATURES_TO_ROLE'),
    ('FEATURE_ADD_PLAFOND'),
    ('FEATURE_GET_ALL_PLAFOND'),
    ('FEATURE_GET_PLAFOND_BY_ID'),
    ('FEATURE_EDIT_PLAFOND'),
    ('FEATURE_REQUEST_LOAN_CUSTOMER'),
    ('FEATURE_GET_ALL_LOAN_CUSTOMER'),
    ('FEATURE_GET_LOAN_CUSTOMER_BY_ID'),
    ('FEATURE_REVIEW_LOAN_MARKETING'),
    ('FEATURE_APPROVE_LOAN_BRANCH_MANAGER'),
    ('FEATURE_APPROVE_LOAN_BACK_OFFICE'),
    ('FEATURE_UPLOAD_LOAN_DOCUMENT'),
    ('FEATURE_ADD_LOAN_STATUS'),
    ('FEATURE_GET_ALL_LOAN_STATUS'),
    ('FEATURE_GET_LOAN_STATUS_BY_ID'),
    ('FEATURE_EDIT_LOAN_STATUS'),
    ('FEATURE_CHANGE_PASSWORD_EMPLOYEE')
) AS FeaturesData(name)
WHERE NOT EXISTS (
    SELECT 1 FROM Features WHERE name = FeaturesData.name
);
