-- Insert role-feature mappings
-- SUPER_ADMIN
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
JOIN features f ON f.name IN (
    'FEATURE_ADD_BRANCHES', 'FEATURE_GET_ALL_BRANCHES', 'FEATURE_GET_BRANCHES_BY_ID',
    'FEATURE_UPDATE_BRANCHES', 'FEATURE_DELETE_BRANCHES', 'FEATURE_GET_ALL_CUSTOMER',
    'FEATURE_FEATURES', 'FEATURE_ADD_EMPLOYEE', 'FEATURE_GET_ALL_EMPLOYEE', 'FEATURE_GET_EMPLOYEE_BY_ID',
    'FEATURE_DELETE_EMPLOYEE', 'FEATURE_PROFILE_EMPLOYEE', 'FEATURE_PEGAWAI_PROFILE',
    'FEATURE_ROLE', 'FEATURE_ROLE_FEATURE', 'FEATURE_USER', 'FEATURE_GET_ALL_PLAFOND',
    'FEATURE_GET_PLAFOND_BY_ID', 'FEATURE_ADD_PLAFOND', 'FEATURE_UPDATE_PLAFOND',
    'FEATURE_DELETE_PLAFOND', 'FEATURE_LOAN_STATUS', 'FEATURE_CREATE_LOAN_REQUEST',
    'FEATURE_REVIEW_LOAN_REQUEST', 'FEATURE_APPROVAL_MARKETING', 'FEATURE_APPROVAL_BM',
    'FEATURE_DISBURSE', 'FEATURE_GET_CUSTOMER_PROFILE', 'FEATURE_UPDATE_CUSTOMER_PROFILE',
    'FEATURE_UPDATE_PEGAWAI_PROFILE', 'FEATURE_DASHBOARD', 'FEATURE_APPROVAL_HISTORY',
    'FEATURE_CHANGE_PASSWORD_EMPLOYEE')
WHERE r.name = 'SUPER_ADMIN';

-- MARKETING
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
JOIN features f ON f.name IN (
    'FEATURE_REVIEW_LOAN_REQUEST', 'FEATURE_APPROVAL_MARKETING', 'FEATURE_DASHBOARD',
    'FEATURE_APPROVAL_HISTORY', 'FEATURE_CHANGE_PASSWORD_EMPLOYEE')
WHERE r.name = 'MARKETING';

-- BRANCH_MANAGER
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
JOIN features f ON f.name IN (
    'FEATURE_REVIEW_LOAN_REQUEST', 'FEATURE_APPROVAL_BM', 'FEATURE_DASHBOARD',
    'FEATURE_APPROVAL_HISTORY', 'FEATURE_CHANGE_PASSWORD_EMPLOYEE')
WHERE r.name = 'BRANCH_MANAGER';

-- BACK_OFFICE
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
JOIN features f ON f.name IN (
    'FEATURE_DISBURSE', 'FEATURE_APPROVAL_HISTORY', 'FEATURE_CHANGE_PASSWORD_EMPLOYEE')
WHERE r.name = 'BACK_OFFICE';

-- CUSTOMER
INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
JOIN features f ON f.name IN (
    'FEATURE_CREATE_LOAN_REQUEST', 'FEATURE_GET_CUSTOMER_PROFILE', 'FEATURE_UPDATE_CUSTOMER_PROFILE')
WHERE r.name = 'CUSTOMER';
